# no parameters, large reply
---
# info from /map topic that deals with origin, etc.
nav_msgs/MapMetaData info

# true if map loaded.
bool loaded

##
# info.resolution
# info.width
# info.height
# geometry_msgs/Pose
# geometry_msgs/Point
# info.origin.position.x
# info.origin.position.y
# info.origin.position.z
# geometry_msgs/Quaternion
# info.origin.orientation.x
# info.origin.orientation.y
# info.origin.orientation.z
# info.origin.orientation.w
