(cl:defpackage tele_presence-srv
  (:use )
  (:export
   "CREATEMAP"
   "<CREATEMAP-REQUEST>"
   "CREATEMAP-REQUEST"
   "<CREATEMAP-RESPONSE>"
   "CREATEMAP-RESPONSE"
   "BASICLAUNCH"
   "<BASICLAUNCH-REQUEST>"
   "BASICLAUNCH-REQUEST"
   "<BASICLAUNCH-RESPONSE>"
   "BASICLAUNCH-RESPONSE"
   "BASICSTOP"
   "<BASICSTOP-REQUEST>"
   "BASICSTOP-REQUEST"
   "<BASICSTOP-RESPONSE>"
   "BASICSTOP-RESPONSE"
   "PICTUREMAP"
   "<PICTUREMAP-REQUEST>"
   "PICTUREMAP-REQUEST"
   "<PICTUREMAP-RESPONSE>"
   "PICTUREMAP-RESPONSE"
  ))

