(cl:defpackage tele_presence-srv
  (:use )
  (:export
   "CREATEMAP"
   "<CREATEMAP-REQUEST>"
   "CREATEMAP-REQUEST"
   "<CREATEMAP-RESPONSE>"
   "CREATEMAP-RESPONSE"
   "PICTUREMAP"
   "<PICTUREMAP-REQUEST>"
   "PICTUREMAP-REQUEST"
   "<PICTUREMAP-RESPONSE>"
   "PICTUREMAP-RESPONSE"
  ))

