/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dave/workspace/telenp/turtlebot_tele_presence/src/tele_presence/srv/MapList.srv
 *
 */


#ifndef TELE_PRESENCE_MESSAGE_MAPLISTRESPONSE_H
#define TELE_PRESENCE_MESSAGE_MAPLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tele_presence/MapListEntry.h>

namespace tele_presence
{
template <class ContainerAllocator>
struct MapListResponse_
{
  typedef MapListResponse_<ContainerAllocator> Type;

  MapListResponse_()
    : map_list()  {
    }
  MapListResponse_(const ContainerAllocator& _alloc)
    : map_list(_alloc)  {
    }



   typedef std::vector< ::tele_presence::MapListEntry_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tele_presence::MapListEntry_<ContainerAllocator> >::other >  _map_list_type;
  _map_list_type map_list;




  typedef boost::shared_ptr< ::tele_presence::MapListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tele_presence::MapListResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MapListResponse_

typedef ::tele_presence::MapListResponse_<std::allocator<void> > MapListResponse;

typedef boost::shared_ptr< ::tele_presence::MapListResponse > MapListResponsePtr;
typedef boost::shared_ptr< ::tele_presence::MapListResponse const> MapListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tele_presence::MapListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tele_presence::MapListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tele_presence

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'tele_presence': ['/home/dave/workspace/telenp/turtlebot_tele_presence/src/tele_presence/msg', '/home/dave/workspace/telenp/turtlebot_tele_presence/src/tele_presence/msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/hydro/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tele_presence::MapListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tele_presence::MapListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tele_presence::MapListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tele_presence::MapListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tele_presence::MapListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tele_presence::MapListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tele_presence::MapListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca5a33dd106a2c24cfd54c927d214957";
  }

  static const char* value(const ::tele_presence::MapListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca5a33dd106a2c24ULL;
  static const uint64_t static_value2 = 0xcfd54c927d214957ULL;
};

template<class ContainerAllocator>
struct DataType< ::tele_presence::MapListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tele_presence/MapListResponse";
  }

  static const char* value(const ::tele_presence::MapListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tele_presence::MapListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
MapListEntry[] map_list\n\
\n\
\n\
================================================================================\n\
MSG: tele_presence/MapListEntry\n\
# One entry in a list of maps.\n\
\n\
# Naming a map is optional.\n\
string name\n\
\n\
# Maps made by the make-a-map app are given a session ID, which is the\n\
# time when the map-making session was started, expressed as seconds\n\
# since the epoch and converted to a string.\n\
string session_id\n\
\n\
# Creation time of this map, in seconds since the epoch.\n\
int64 date\n\
\n\
# Unique ID of this map.\n\
string map_id\n\
";
  }

  static const char* value(const ::tele_presence::MapListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tele_presence::MapListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MapListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tele_presence::MapListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tele_presence::MapListResponse_<ContainerAllocator>& v)
  {
    s << indent << "map_list[]" << std::endl;
    for (size_t i = 0; i < v.map_list.size(); ++i)
    {
      s << indent << "  map_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tele_presence::MapListEntry_<ContainerAllocator> >::stream(s, indent + "    ", v.map_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELE_PRESENCE_MESSAGE_MAPLISTRESPONSE_H
