(cl:defpackage tele_presence-msg
  (:use )
  (:export
   "<MAPWITHMETADATA>"
   "MAPWITHMETADATA"
   "<MAPLISTENTRYLIST>"
   "MAPLISTENTRYLIST"
   "<MAPLISTENTRY>"
   "MAPLISTENTRY"
   "<MAPLISTELEMENT>"
   "MAPLISTELEMENT"
   "<MAPWITHMETADATA>"
   "MAPWITHMETADATA"
   "<MAPLISTENTRYLIST>"
   "MAPLISTENTRYLIST"
   "<MAPLISTENTRY>"
   "MAPLISTENTRY"
   "<MAPLISTELEMENT>"
   "MAPLISTELEMENT"
  ))

