# a test version of the app.yaml used for the telenp project.
application: awesometelenp

version: 12
runtime: python27
api_version: 1
threadsafe: false

# Set cache duration to 0 for development
default_expiration: "0m"

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: .*
  script: main.py
