# a test version of the app.yaml used for the telenp project.
application: awesometelenp

version: 14
runtime: python27
api_version: 1
threadsafe: false

# Set cache duration to 0 for development
# comment out so that maps can be shared!!
# default_expiration: "0m"

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

#- url: /send
#  script: main.py
  
- url: /*
  script: main.py
  

