# a test version of the app.yaml used for development. This is not intended to be checked in
application: awesometelenp

version: 2
runtime: python27
api_version: 1
threadsafe: false

# Set cache duration to 0 for development
default_expiration: "0m"

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: .*
  script: main.py
